create table if not exists public.adoptions (
  id bigint generated by default as identity primary key,
  adopter_name text not null check (char_length(adopter_name) between 1 and 24),
  plant_name text not null check (char_length(plant_name) between 1 and 24),
  plant_type text not null,
  light_level text not null,
  watering_habit text not null,
  has_pets boolean not null default false,
  experience_level text not null,
  created_at timestamptz not null default now()
);

alter table public.adoptions enable row level security;

create policy "Public can create adoptions"
on public.adoptions for insert to anon
with check (true);

create policy "Public can view adoptions"
on public.adoptions for select to anon
using (true);

grant select, insert on public.adoptions to anon;
grant usage, select on sequence public.adoptions_id_seq to anon;
